server:
  port: 8090

spring:
  application:
    name: banking-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Swayam792/banking-configurations.git
          search-paths: configuration
          default-label: main
          username:
          password: