server:
  port: 8083

spring:
  application:
    name: banking-user-service
  datasource:
    url: jdbc:mysql://localhost:3306/bankingdb
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
